In [31]:
from tensorflow.keras.preprocessing.text import one_hot

In [32]:
## Sentence
sent = [ 'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',
]

In [33]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [34]:
## Define the vocabulary size
voc_size = 10000

In [35]:
## One hot Represenetation
one_hot_rep = [one_hot(words,voc_size)for words in sent]
one_hot_rep

[[3370, 1127, 8371, 2592],
 [3370, 1127, 8371, 6460],
 [3370, 75, 8371, 4423],
 [5715, 5682, 3303, 2722, 9308],
 [5715, 5682, 3303, 2722, 1612],
 [2793, 3370, 9160, 8371, 5753],
 [4377, 9080, 9555, 2722]]

In [36]:
## Word Embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [37]:
import numpy as np

In [38]:
## Make the sentences of equal sizes by using pad sequence

sent_length = 8
embedded_docs = pad_sequences(one_hot_rep, padding = 'pre',maxlen = sent_length)

In [39]:
embedded_docs

array([[   0,    0,    0,    0, 3370, 1127, 8371, 2592],
       [   0,    0,    0,    0, 3370, 1127, 8371, 6460],
       [   0,    0,    0,    0, 3370,   75, 8371, 4423],
       [   0,    0,    0, 5715, 5682, 3303, 2722, 9308],
       [   0,    0,    0, 5715, 5682, 3303, 2722, 1612],
       [   0,    0,    0, 2793, 3370, 9160, 8371, 5753],
       [   0,    0,    0,    0, 4377, 9080, 9555, 2722]], dtype=int32)

In [40]:
## Feature representation
dim = 10

In [41]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [42]:
model.build((None, sent_length))  # Specify input shape
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [43]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step


array([[[ 3.91687788e-02,  3.26960795e-02,  4.91344817e-02,
         -2.86227949e-02,  3.82584333e-03, -2.92592403e-02,
          3.63234989e-02, -3.98621447e-02,  2.92026885e-02,
         -1.19558349e-02],
        [ 3.91687788e-02,  3.26960795e-02,  4.91344817e-02,
         -2.86227949e-02,  3.82584333e-03, -2.92592403e-02,
          3.63234989e-02, -3.98621447e-02,  2.92026885e-02,
         -1.19558349e-02],
        [ 3.91687788e-02,  3.26960795e-02,  4.91344817e-02,
         -2.86227949e-02,  3.82584333e-03, -2.92592403e-02,
          3.63234989e-02, -3.98621447e-02,  2.92026885e-02,
         -1.19558349e-02],
        [ 3.91687788e-02,  3.26960795e-02,  4.91344817e-02,
         -2.86227949e-02,  3.82584333e-03, -2.92592403e-02,
          3.63234989e-02, -3.98621447e-02,  2.92026885e-02,
         -1.19558349e-02],
        [ 2.64611579e-02,  4.92507927e-02, -2.38817818e-02,
          4.26402576e-02, -3.72190103e-02,  4.17343043e-02,
          3.39074843e-02,  1.76674128e-03,  2.950171

In [44]:
# first sentence
embedded_docs[0]

array([   0,    0,    0,    0, 3370, 1127, 8371, 2592], dtype=int32)

In [47]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step


array([[[ 0.03916878,  0.03269608,  0.04913448, -0.02862279,
          0.00382584, -0.02925924,  0.0363235 , -0.03986214,
          0.02920269, -0.01195583],
        [ 0.03916878,  0.03269608,  0.04913448, -0.02862279,
          0.00382584, -0.02925924,  0.0363235 , -0.03986214,
          0.02920269, -0.01195583],
        [ 0.03916878,  0.03269608,  0.04913448, -0.02862279,
          0.00382584, -0.02925924,  0.0363235 , -0.03986214,
          0.02920269, -0.01195583],
        [ 0.03916878,  0.03269608,  0.04913448, -0.02862279,
          0.00382584, -0.02925924,  0.0363235 , -0.03986214,
          0.02920269, -0.01195583],
        [ 0.02646116,  0.04925079, -0.02388178,  0.04264026,
         -0.03721901,  0.0417343 ,  0.03390748,  0.00176674,
          0.02950171, -0.01064597],
        [ 0.00386429, -0.02134236,  0.0058426 ,  0.04087   ,
          0.01413412, -0.02384087,  0.00194403, -0.01755697,
          0.04892356, -0.02249773],
        [-0.0219144 , -0.00211569,  0.03039065, -0.0